sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i --save-dev eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react
script:
  - eslint src/ --ext .jsx
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
