sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7.4.0'
before_install:
  - npm i -g npm@^4.0.0
  - npm i -g eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react
script:
  - eslint src/ --ext .jsx
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
